### ISSUE TITLE
error when upgrade flutter to 2.5

### ISSUE THREAD

**Issue by aseph8083** [kholifanalfon/bs_flutter_selectbox#2]
.pub-cache/hosted/pub.dartlang.org/bs_flutter_selectbox-1.2.2/lib/src/components/bs_wrapper_option.dart:108:14: Error: A value of type 'bool' can't be returned from a function with return type 'KeyEventResult'.
 - 'KeyEventResult' is from 'package:flutter/src/widgets/focus_manager.dart' ('/C:/android/flutter/packages/flutter/lib/src/widgets/focus_manager.dart').
      return false;

**Comment by srcho** [comment]
i have same problem

**Comment by jheimes-silveira** [comment]
Estou com o mesmo problema

**Comment by moradnajem** [comment]
same problem

**Comment by moradnajem** [comment]
> same problem

https://github.com/kholifanalfon/bs_flutter_selectbox/pull/4/commits/0c6d329fc9a5c9c43e810919576c6a338406916f
