### ISSUE TITLE
how get selected value ?

### ISSUE THREAD

**Issue by gokul222** [kholifanalfon/bs_flutter_selectbox#7]
after select value that values how to get

**Comment by gokul222** [comment]
@huahouye @kholifanalfon @jobdesc-kholifan

**Comment by huahouye** [comment]
Hi @gokul222 ,Do you mean select callback? If so, please see my update example PR [here](https://github.com/kholifanalfon/bs_flutter_selectbox/pull/8/files#diff-72fd825ad17ce7800a2078e06f0dff1e12836ee59760465e78d9a5d222cebd15)

**Comment by gokul222** [comment]
@huahouye  thanks buddy
